trigger:
  - master

resources:
  repositories:
    - repository: rosci
      type: github
      name: ascentai/azure_ros_ci
      endpoint: ascentai
      ref: switch_to_20_04

jobs:
  - template: ros-template.yml@rosci
    parameters:
      rosdistro: "noetic"
      dockerImage: ""
      pkgToTest: "20.04-noetic-cuda11.8-trt8:master"
      name: "install"
      installMode: true
      runClangTidy: true
