trigger:
  - master

resources:
  repositories:
    - repository: rosci
      type: github
      name: ascentai/azure_ros_ci
      endpoint: ascentai

jobs:
  - template: ros-template.yml@rosci
    parameters:
      rosdistro: "noetic"
      dockerImage: "cudagl11.0-cudnn8-devel-tensorrt8.4-ubuntu20.04-rosnoeticbase-ssh"
      pkgToTest: ""
      name: "install"
      installMode: true
      runClangTidy: true
